apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cnpg-psp-user
  namespace: cnpg-cluster
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - cnpg-pods
