apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cnpg-psp-binding
  namespace: cnpg-cluster
roleRef:
  kind: Role
  name: cnpg-psp-user
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: cnpg-manager
  namespace: cnpg-system
