version: '3.8'

services:
  organizer-app:
    image: ghcr.io/hackload-kz/infra:sha-1c161c0
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    ports:
      - "3300:3300"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:password@db:5432/hackload_organizer
      - NEXTAUTH_URL=http://localhost:3300
      - NEXTAUTH_SECRET=your-secret-key-change-in-production
      - AUTH_TRUST_HOST=http://localhost:3300
      - ADMIN_USERS=admin@hackload.kz:admin123,organizer@hackload.kz:organizer123
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=hackload_organizer
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
