apiVersion: batch/v1
kind: CronJob
metadata:
  name: k6-steps-sync
  namespace: hub
spec:
  schedule: "* * * * *"  # Каждую минуту
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: k6-sync
            image: curlimages/curl:latest
            command:
            - /bin/sh
            - -c
            - |
              echo "Starting K6 steps sync at $(date)"
              
              # Выполнить HTTP запрос к API
              RESPONSE=$(curl -s -w "%{http_code}" -X POST \
                -H "Authorization: Bearer $K6_SYNC_API_KEY" \
                -H "Content-Type: application/json" \
                "$ORGANIZER_APP_URL/api/dashboard/load-testing/sync-status-steps")
              
              HTTP_CODE="${RESPONSE: -3}"
              BODY="${RESPONSE%???}"
              
              echo "HTTP Code: $HTTP_CODE"
              echo "Response: $BODY"
              
              if [ "$HTTP_CODE" -eq 200 ]; then
                echo "✅ K6 sync completed successfully"
                exit 0
              else
                echo "❌ K6 sync failed with HTTP $HTTP_CODE"
                exit 1
              fi
            env:
            - name: K6_SYNC_API_KEY
              valueFrom:
                secretKeyRef:
                  name: k6-sync-secret
                  key: api-key
            - name: ORGANIZER_APP_URL
              value: "http://hub-service.hub.svc.cluster.local:3000"
          restartPolicy: OnFailure
          
---
apiVersion: v1
kind: Secret
metadata:
  name: k6-sync-secret
  namespace: hub
type: Opaque
data:
  # echo -n "your-api-key" | base64
  api-key: eW91ci1hcGkta2V5