apiVersion: v1
kind: Service
metadata:
  name: hackload-job-service
  namespace: hub
  labels:
    app: hackload-job-service
    component: background-jobs
spec:
  type: ClusterIP
  ports:
  - name: health
    port: 8080
    targetPort: health
    protocol: TCP
  - name: metrics
    port: 9090
    targetPort: metrics
    protocol: TCP
  selector:
    app: hackload-job-service